# Generated by Django 2.1.7 on 2019-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190516_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='video', verbose_name='封面视频'),
        ),
    ]
